services:
  postgres:
    image: postgres:16.11
    container_name: real-estate-booking-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "16433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - enp-ai-bridge-nt

  localstack:
    image: gresau/localstack-persist:4.13.1
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=s3,sqs,sns,lambda,secretsmanager,eventbridge
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # will be needed by lambda providers
      - "./volumes/localstack:/persisted-data"
    networks:
      - enp-ai-bridge-nt

volumes:
  postgres_data:

networks:
  enp-ai-bridge-nt:
    external: true